/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

    epicachievements: [{type: 'autogenerated', dirName: 'epicachievements'}],
    woolwars: [{type: 'autogenerated', dirName: 'wool-wars'}],
    guilds: [{type: 'autogenerated', dirName: 'guilds'}],
    guildstasks: [{type: 'autogenerated', dirName: 'guilds-tasks'}],
    usefulstuff: [{type: 'autogenerated', dirName: 'useful-stuff'}]

};

module.exports = sidebars;
