/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  achievements: [{type: 'autogenerated', dirName: 'achievements'}],
  woolwars: [{type: 'autogenerated', dirName: 'wool-wars'}],
  guilds: [{type: 'autogenerated', dirName: 'guilds'}],
  
};

module.exports = sidebars;
